development:
  adapter: postgresql
  encoding: utf8
  database: tweet_aquarium_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: tweet_aquarium_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tweet_aquarium_production
  pool: 5
  username:
  password:
