# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2263aa49a421d518bc4ac0865ddf4afff44eccfe374df0eac0b4dda9f0b1efc61c927e4c0f4f7d1103f788b39a5763931b85e5c1a73ab498c6bf09b8f03ad8

test:
  secret_key_base: d629dea39cb9cc85492d1bbe03b8c05f726e6c3c04af6fa667557ccef4ae56c7bb03279115ee2bc0bbb240cee1c0bfda753bb819232f5d86c1520c3741f595f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
